/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sa;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author pedro_hn_silva
 */
public class TelaFuncionario extends javax.swing.JFrame {

    ArrayList<Funcionario> listaFuncionarios = new ArrayList<>();

    /**
     * Creates new form TelaFuncionario
     */
    public TelaFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        campoNomeFuncionario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoCpfFuncionario = new javax.swing.JTextField();
        campoMatriculaFuncionario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoIdadeFuncionario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnAddFuncionario = new javax.swing.JButton();
        btnListarFuncionarios = new javax.swing.JButton();
        btnEditarFuncionario = new javax.swing.JButton();
        btnExcluirFuncionario = new javax.swing.JButton();
        btnFuncionariosDoMes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro - Funcionário");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Siemens Slab SC Black", 0, 36)); // NOI18N
        jLabel2.setText("Funcionário");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnVoltar.setBackground(new java.awt.Color(204, 204, 255));
        btnVoltar.setText("Voltar");
        btnVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Nome");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("CPF");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Matrícula");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Idade");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/funcionarioImg.png"))); // NOI18N

        btnAddFuncionario.setBackground(new java.awt.Color(255, 255, 255));
        btnAddFuncionario.setForeground(new java.awt.Color(153, 204, 255));
        btnAddFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconeAdicionarFunc.png"))); // NOI18N
        btnAddFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFuncionarioActionPerformed(evt);
            }
        });

        btnListarFuncionarios.setBackground(new java.awt.Color(255, 255, 255));
        btnListarFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconeListarFunc.png"))); // NOI18N
        btnListarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarFuncionariosActionPerformed(evt);
            }
        });

        btnEditarFuncionario.setBackground(new java.awt.Color(255, 255, 255));
        btnEditarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconeEditarFunc.png"))); // NOI18N
        btnEditarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarFuncionarioActionPerformed(evt);
            }
        });

        btnExcluirFuncionario.setBackground(new java.awt.Color(255, 255, 255));
        btnExcluirFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconeExcluirFunc.png"))); // NOI18N
        btnExcluirFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirFuncionarioActionPerformed(evt);
            }
        });

        btnFuncionariosDoMes.setText("Funcionários do mês");
        btnFuncionariosDoMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncionariosDoMesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVoltar)
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel2))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(campoCpfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(campoMatriculaFuncionario)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(campoIdadeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAddFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnExcluirFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnListarFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnFuncionariosDoMes)
                        .addGap(164, 164, 164))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnVoltar)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jLabel7)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoIdadeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCpfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoMatriculaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(btnFuncionariosDoMes)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAddFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnExcluirFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnListarFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        new App().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnAddFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFuncionarioActionPerformed
        if(verificarCampos()){
            JOptionPane.showMessageDialog(null, "Favor preencher todos os campos corretamente.", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            cadastrarFuncionario();
        }
    }//GEN-LAST:event_btnAddFuncionarioActionPerformed

    private void btnListarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarFuncionariosActionPerformed
        listarFuncionarios();

    }//GEN-LAST:event_btnListarFuncionariosActionPerformed

    private void btnEditarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarFuncionarioActionPerformed
        if(verificarMatricula()){
            JOptionPane.showMessageDialog(null, "Favor preencher o campo da matrícula.", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            editarFuncionario();
        }
    }//GEN-LAST:event_btnEditarFuncionarioActionPerformed

    private void btnExcluirFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirFuncionarioActionPerformed
        if(verificarMatricula()){
            JOptionPane.showMessageDialog(null, "Favor preencher o campo da matrícula.", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            excluirFuncionario();
        }
    }//GEN-LAST:event_btnExcluirFuncionarioActionPerformed

    private void btnFuncionariosDoMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncionariosDoMesActionPerformed
        new TelaFuncDoMes().setVisible(true);
    }//GEN-LAST:event_btnFuncionariosDoMesActionPerformed
    
    public boolean verificarCampos() {
	if (campoNomeFuncionario.getText().equals(null) || campoNomeFuncionario.getText().equals("") || campoIdadeFuncionario.getText().equals(null) || campoIdadeFuncionario.getText().equals("") || campoCpfFuncionario.getText().equals(null) || campoCpfFuncionario.getText().equals("") || campoMatriculaFuncionario.getText().equals(null) || campoMatriculaFuncionario.getText().equals("")) {
            return true;
        } else {
            return false;
        }
    }
    
    public boolean verificarMatricula(){
        if (campoMatriculaFuncionario.getText().equals(null) || campoMatriculaFuncionario.getText().equals("")){
            return true;
        } else {
            return false;
        }
    }
        
    public void cadastrarFuncionario() {
        String nome = campoNomeFuncionario.getText();
        int idade = Integer.parseInt(campoIdadeFuncionario.getText());
        String Cpf = campoCpfFuncionario.getText();
        String matricula = campoMatriculaFuncionario.getText();

        Funcionario func = new Funcionario(nome, idade, Cpf, matricula);
        listaFuncionarios.add(func);
        JOptionPane.showMessageDialog(null, "Cadastro realizado", "Cadastro concluído", JOptionPane.INFORMATION_MESSAGE);

        campoNomeFuncionario.setText(null);
        campoIdadeFuncionario.setText(null);
        campoCpfFuncionario.setText(null);
        campoMatriculaFuncionario.setText(null);
    }

    public void listarFuncionarios() {
        String funcs = "Funcionários:\n";
        
        if(listaFuncionarios.size() == 0){
            JOptionPane.showMessageDialog(this, "Não há funcionários cadastrados");
        }
        else{
        for (Funcionario func : listaFuncionarios) {
            funcs += "\n________\n"
                    + "Nome: " + func.getNome() + "\n"
                    + "Idade: " + func.getIdade() + "\n"
                    + "CPF: " + func.getCpf() + "\n"
                    + "Matrícula: " + func.getMatriculaFuncionario();
        }
        JOptionPane.showMessageDialog(this, funcs);
        }
    }

    public void editarFuncionario() {
        Object[] options = {"Nome", "Idade", "CPF", "Matrícula"};

        for (Funcionario func : listaFuncionarios) {

            String matricula = campoMatriculaFuncionario.getText();

            if (func.getMatriculaFuncionario().equals(matricula)) {
                int infoEdit = JOptionPane.showOptionDialog(null, "Qual informação de " + func.getNome() + " deseja editar? ", "Opções de edição", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
                switch (infoEdit) {
                    case 0:
                        String novoNome = JOptionPane.showInputDialog(null, "Deseja substituir " + func.getNome() + " por qual nome?");
                        func.setNome(novoNome);
                        JOptionPane.showMessageDialog(this, "Edição realizada!", "Edição completa", JOptionPane.INFORMATION_MESSAGE);
                        break;
                    case 1:
                        int novaIdade = Integer.parseInt(JOptionPane.showInputDialog(null, "Deseja substituir " + func.getIdade() + " por qual idade?"));
                        func.setIdade(novaIdade);
                        JOptionPane.showMessageDialog(this, "Edição realizada!", "Edição completa", JOptionPane.INFORMATION_MESSAGE);
                        break;

                    case 2:
                        String novoCPF = JOptionPane.showInputDialog(null, "Deseja substituir " + func.getCpf() + " por qual CPF?");
                        func.setCpf(novoCPF);
                        JOptionPane.showMessageDialog(this, "Edição realizada!", "Edição completa", JOptionPane.INFORMATION_MESSAGE);
                        break;

                    case 3:
                        String novaMatricula = JOptionPane.showInputDialog(null, "Deseja substituir " + func.getMatriculaFuncionario() + " por qual matrícula?");
                        func.setMatriculaFuncionario(novaMatricula);
                        JOptionPane.showMessageDialog(this, "Edição realizada!", "Edição completa", JOptionPane.INFORMATION_MESSAGE);
                        break;

                }
                break;
            }
        }
    }

    public void excluirFuncionario() {
        for (Funcionario func : listaFuncionarios) {
            if (campoMatriculaFuncionario.getText().equals(func.getMatriculaFuncionario())) {
                listaFuncionarios.remove(func);
                JOptionPane.showMessageDialog(this, "Exclusão concluída!");
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFuncionario;
    private javax.swing.JButton btnEditarFuncionario;
    private javax.swing.JButton btnExcluirFuncionario;
    private javax.swing.JButton btnFuncionariosDoMes;
    private javax.swing.JButton btnListarFuncionarios;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JTextField campoCpfFuncionario;
    private javax.swing.JTextField campoIdadeFuncionario;
    private javax.swing.JTextField campoMatriculaFuncionario;
    private javax.swing.JTextField campoNomeFuncionario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
