/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sa;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author pedro_hn_silva
 */
public class TelaAluno extends javax.swing.JFrame {

    ArrayList<Aluno> listaAlunos = new ArrayList<>();

    /**
     * Creates new form TelaAluno
     */
    public TelaAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnEditarAluno = new javax.swing.JButton();
        btnExcluirAluno = new javax.swing.JButton();
        btnAddAluno = new javax.swing.JButton();
        btnListarAluno = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoNomeAluno = new javax.swing.JTextField();
        campoIdadeAluno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoCPFAluno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoMatriculaAluno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoHorarioAluno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro - Aluno");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Siemens Slab SC Black", 0, 36)); // NOI18N
        jLabel1.setText("Aluno");

        btnEditarAluno.setBackground(new java.awt.Color(255, 255, 255));
        btnEditarAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconeEditarAluno.png"))); // NOI18N
        btnEditarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarAlunoActionPerformed(evt);
            }
        });

        btnExcluirAluno.setBackground(new java.awt.Color(255, 255, 255));
        btnExcluirAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconeExcluirAluno.png"))); // NOI18N
        btnExcluirAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirAlunoActionPerformed(evt);
            }
        });

        btnAddAluno.setBackground(new java.awt.Color(255, 255, 255));
        btnAddAluno.setForeground(new java.awt.Color(153, 204, 255));
        btnAddAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconeAdicionarAluno.png"))); // NOI18N
        btnAddAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAlunoActionPerformed(evt);
            }
        });

        btnListarAluno.setBackground(new java.awt.Color(255, 255, 255));
        btnListarAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconeListarAluno.png"))); // NOI18N
        btnListarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarAlunoActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alunoImg.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Idade");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("CPF");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Nome");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Matrícula");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Horário da academia");

        jLabel8.setText("Formato 24h");

        btnVoltar.setBackground(new java.awt.Color(153, 204, 255));
        btnVoltar.setText("Voltar");
        btnVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVoltar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAddAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnExcluirAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnListarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(campoCPFAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(campoMatriculaAluno)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(campoIdadeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(157, 157, 157))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(162, 162, 162))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(194, 194, 194))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campoHorarioAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(200, 200, 200))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoIdadeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCPFAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoMatriculaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoHorarioAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAddAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnExcluirAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnListarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirAlunoActionPerformed
        if (verificarMatricula()) {
            JOptionPane.showMessageDialog(null, "Favor preencher o campo da matrícula.", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            excluirAluno();
        }
    }//GEN-LAST:event_btnExcluirAlunoActionPerformed

    private void btnAddAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAlunoActionPerformed
        if (verificarCampos()) {
            JOptionPane.showMessageDialog(null, "Favor preencher todos os campos corretamente.", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            cadastrarAluno();
        }
    }//GEN-LAST:event_btnAddAlunoActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        new App().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnListarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarAlunoActionPerformed
        listarAlunos();
    }//GEN-LAST:event_btnListarAlunoActionPerformed

    private void btnEditarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarAlunoActionPerformed
        if (verificarMatricula()) {
            JOptionPane.showMessageDialog(null, "Favor preencher o campo da matrícula.", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            editarAluno();
        }
    }//GEN-LAST:event_btnEditarAlunoActionPerformed

    public boolean verificarCampos() {
        if (campoNomeAluno.getText().equals(null) || campoNomeAluno.getText().equals("") || campoIdadeAluno.getText().equals(null) || campoIdadeAluno.getText().equals("") || campoCPFAluno.getText().equals(null) || campoCPFAluno.getText().equals("") || campoMatriculaAluno.getText().equals(null) || campoMatriculaAluno.getText().equals("") || campoHorarioAluno.getText().equals(null) || campoHorarioAluno.getText().equals("")) {
            return true;
        } else {
            return false;
        }
    }

    public boolean verificarMatricula() {
        if (campoMatriculaAluno.getText().equals(null) || campoMatriculaAluno.getText().equals("")) {
            return true;
        } else {
            return false;
        }
    }

    public void cadastrarAluno() {
        String nome = campoNomeAluno.getText();
        int idade = Integer.parseInt(campoIdadeAluno.getText());
        String cpf = campoCPFAluno.getText();
        String matriculaAluno = campoMatriculaAluno.getText();
        String horario = campoHorarioAluno.getText();

        Aluno aluno = new Aluno(nome, idade, cpf, matriculaAluno, horario);
        listaAlunos.add(aluno);
        JOptionPane.showMessageDialog(null, "Cadastro realizado", "Cadastro concluído", JOptionPane.INFORMATION_MESSAGE);

        campoNomeAluno.setText(null);
        campoIdadeAluno.setText(null);
        campoCPFAluno.setText(null);
        campoMatriculaAluno.setText(null);
        campoHorarioAluno.setText(null);
    }

    public void listarAlunos() {
        String alunos = "Alunos:\n";
        if(listaAlunos.size() == 0){
            JOptionPane.showMessageDialog(this, "Não há alunos cadastrados");
        }
        else{
            for (Aluno aluno : listaAlunos) {
                alunos += "\n________\n"
                        + "Nome: " + aluno.getNome() + "\n"
                        + "Idade: " + aluno.getIdade() + "\n"
                        + "CPF: " + aluno.getCpf() + "\n"
                        + "Matrícula: " + aluno.getMatriculaAluno() + "\n"
                        + "Horário: " + aluno.getHorario();
            }
            JOptionPane.showMessageDialog(this, alunos);
        }
    }

    public void editarAluno() {
        Object[] options = {"Nome", "Idade", "CPF", "Matrícula", "Horário"};

        for (Aluno aluno : listaAlunos) {

            String matricula = campoMatriculaAluno.getText();

            if (aluno.getMatriculaAluno().equals(matricula)) {
                int infoEdit = JOptionPane.showOptionDialog(null, "Qual informação de " + aluno.getNome() + " deseja editar? ", "Opções de edição", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
                switch (infoEdit) {
                    case 0:
                        String novoNome = JOptionPane.showInputDialog(null, "Deseja substituir " + aluno.getNome() + " por qual nome?");
                        aluno.setNome(novoNome);
                        JOptionPane.showMessageDialog(this, "Edição realizada!", "Edição completa", JOptionPane.INFORMATION_MESSAGE);
                        break;
                    case 1:
                        int novaIdade = Integer.parseInt(JOptionPane.showInputDialog(null, "Deseja substituir " + aluno.getIdade() + " por qual idade?"));
                        aluno.setIdade(novaIdade);
                        JOptionPane.showMessageDialog(this, "Edição realizada!", "Edição completa", JOptionPane.INFORMATION_MESSAGE);
                        break;

                    case 2:
                        String novoCPF = JOptionPane.showInputDialog(null, "Deseja substituir " + aluno.getCpf() + " por qual CPF?");
                        aluno.setCpf(novoCPF);
                        JOptionPane.showMessageDialog(this, "Edição realizada!", "Edição completa", JOptionPane.INFORMATION_MESSAGE);
                        break;

                    case 3:
                        String novaMatricula = JOptionPane.showInputDialog(null, "Deseja substituir " + aluno.getMatriculaAluno() + " por qual matrícula?");
                        aluno.setMatriculaAluno(novaMatricula);
                        JOptionPane.showMessageDialog(this, "Edição realizada!", "Edição completa", JOptionPane.INFORMATION_MESSAGE);
                        break;

                    case 4:
                        String novoHorário = JOptionPane.showInputDialog(null, "Deseja substituir " + aluno.getHorario() + " por qual horario?");
                        aluno.setHorario(novoHorário);
                        JOptionPane.showMessageDialog(this, "Edição realizada!", "Edição completa", JOptionPane.INFORMATION_MESSAGE);
                        break;
                }
                break;
            }
        }
    }

    public void excluirAluno() {
        for (Aluno aluno : listaAlunos) {
            if (campoMatriculaAluno.getText().equals(aluno.getMatriculaAluno())) {
                listaAlunos.remove(aluno);
                JOptionPane.showMessageDialog(this, "Exclusão concluída!");
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAluno;
    private javax.swing.JButton btnEditarAluno;
    private javax.swing.JButton btnExcluirAluno;
    private javax.swing.JButton btnListarAluno;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JTextField campoCPFAluno;
    private javax.swing.JTextField campoHorarioAluno;
    private javax.swing.JTextField campoIdadeAluno;
    private javax.swing.JTextField campoMatriculaAluno;
    private javax.swing.JTextField campoNomeAluno;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
